project_id = "zispltnkyotdmxuqsofu"

[functions.send-email-otp]
verify_jwt = false

[functions.verify-email-otp]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.match-assistant]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-subscription-notification]
verify_jwt = false
